# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/emb_opt',
                'doc_host': 'https://DarkMatterAI.github.io',
                'git_url': 'https://github.com/DarkMatterAI/emb_opt',
                'lib_path': 'emb_opt'},
  'syms': {'emb_opt.core': {'emb_opt.core.foo': ('core.html#foo', 'emb_opt/core.py')}}}
