# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_score.ipynb.

# %% auto 0
__all__ = ['ScoreModule']

# %% ../nbs/05_score.ipynb 3
from .imports import *
from .core import Module, Executor
from .schemas import Item, Query, Batch, ScoreFunction, ScoreResponse

# %% ../nbs/05_score.ipynb 4
class ScoreModule(Module):
    def __init__(self, function: ScoreFunction):
        super().__init__(ScoreResponse, function)
        
    def gather_inputs(self, batch: Batch) -> (List[Tuple], List[Item]):
        idxs, inputs = batch.flatten_query_results()
        return (idxs, inputs)
    
    def scatter_results(self, batch: Batch, idxs: List[Tuple], results: List[ScoreResponse]):
        for (q_idx, r_idx), result in zip(idxs, results):
            batch_item = batch.get_item(q_idx, r_idx)
            batch_item.score = result.score
            if result.data:
                batch_item.data.update(result.data)
                
            if not result.valid:
                batch_item.data['_internal']['remove'] = True
                batch_item.data['_internal']['remove_details'] = 'score response invalid'
