# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_faiss.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/03_faiss.ipynb 3
from ..imports import *
from ..core import QueryDataset, QueryResult, VectorDatabase
import faiss
